import Head from "next/head";
import Temp from "../src/components/units/login/temp";

// 스타일링 변수 예시
import { StyleTestDiv } from "./StylesTest";
export default function Home() {
  return (
    <>
      <Head>
        <title>로맨스가 필요해💕</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Temp />
      {/* 스타일링 변수 예시 */}
      <StyleTestDiv>redreded하이하이하이</StyleTestDiv>
    </>
  );
}
