import Head from "next/head";
import Main from "../src/components/units/main/Main.container";

export default function Home() {
  return (
    <>
      <Head>
        <title>로맨스가 필요해💕</title>
        <meta http-equiv="Expires" content="Sun, 07 Aug 2022 18:51:54 GMT" />
        <meta http-equiv="Expires" content="0" />
        <meta
          http-equiv="Cache-Control"
          content="no-cache, no-store, must-revalidate"
        />
        <meta name="referrer" content="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </>
  );
}
